AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 30

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: org.example.aws.lambda.apis.CreateOrderLambda::createOrder
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  ReadOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: org.example.aws.lambda.apis.ReadOrderLambda::getOrders
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
