AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: org.example.aws.lambda.apis.CreateOrderLambda::handleRcreateOrder
      Runtime: java11
      MemorySize: 512
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST